import Head from 'next/head'
import PostList from '@/components/post-list'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-3xl">
        <h1 className="mb-10 text-4xl">Hello World!</h1>
        <PostList />
      </main>
    </>
  )
}
